#Comando para el Nombre del Flujo
name: CI pipeline

#Indica cuando se ejecuta el flujo:
on:
  pull_request:
  push:
    branches:
      - develop

#Acciones que se ejecutaran en el sevidor
jobs: 
  frontend-build:
    runs-on: ubuntu-latest

    defaults: 
      run: 
        working-directory: frontend

    steps:
      - name: Checkout repository (git clone)
        uses: actions/checkout@v4

      - name: Setup node (instalar node)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install

      - name: Construir el frontend
        run: npm run build